In [1]:
import numpy as np

In [2]:
def get_element_count_from_shape(shape):
    output = 1
    for dimension in shape:
        output *= dimension
    return output

def array_info(input_arr):
    print(input_arr)
    print('shape:', input_arr.shape, '     elements:', get_element_count_from_shape(input_arr.shape))

def reshape_verbose(old_arr, new_shape):
    print
    print
    array_info(old_arr)
    new_arr = np.reshape(old_arr, new_shape)
    print
    print '-> reshape(' + str(new_shape) + ') ->'
    print
    array_info(new_arr)
    print
    print
    return new_arr


In [3]:
flat = np.array(range(12))
array_info(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)


the shape of flat is [12] (or (12,)) and it holds 12 elements

we can reshape it into any other set of dimensions that also hold 12 elements

(6, 2) holds 6 * 2 = 12 elements, the same as our flat array. so we can reshape to that new shape

same goes for

shape (2, 6) = 2 * 6 = 12 elements

and

shape (2, 2, 3) = 2 \* 2 \* 3 = 12 elements

In [4]:
six_two = reshape_verbose(flat, [6, 2])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([6, 2]) ->

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
('shape:', (6, 2), '     elements:', 12)




In [5]:
two_six = reshape_verbose(flat, [2, 6])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([2, 6]) ->

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
('shape:', (2, 6), '     elements:', 12)




In [6]:
two_two_three = reshape_verbose(flat, [2, 2, 3])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([2, 2, 3]) ->

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
('shape:', (2, 2, 3), '     elements:', 12)




I read that the underlying memory is unchanged after reshaping, that means we should be able to shape all of the arrays we just generated in to equal arrays of a specific dimension. Let's test that

In [7]:
destination_dims = [3, 2, 2]
maybe_equal_three_two_twos = []
maybe_equal_three_two_twos.append(np.reshape(flat, destination_dims))
maybe_equal_three_two_twos.append(np.reshape(six_two, destination_dims))
maybe_equal_three_two_twos.append(np.reshape(two_six, destination_dims))
maybe_equal_three_two_twos.append(np.reshape(two_two_three, destination_dims))
# maybe_equal_three_two_twos.append(reshape_verbose(two_two_three, destination_dims))

are_all_equal = True
for arrA in maybe_equal_three_two_twos:
    for arrB in maybe_equal_three_two_twos:
        are_all_equal = are_all_equal and np.array_equal(arrA, arrB)
print('all of the different sources ended up the same when reshaped:', are_all_equal)

('all of the different sources ended up the same when reshaped:', True)


I have seen reshape (array, [dim1, dim2]) and also (array (dim1, dim2)), are these the same?

In [8]:
four_three = reshape_verbose(two_two_three, [4, 3])
four_three_alt = reshape_verbose(two_two_three, (4, 3))

print('[] is the same as () :', np.array_equal(four_three, four_three_alt))



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
('shape:', (2, 2, 3), '     elements:', 12)

-> reshape([4, 3]) ->

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
('shape:', (4, 3), '     elements:', 12)




[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
('shape:', (2, 2, 3), '     elements:', 12)

-> reshape((4, 3)) ->

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
('shape:', (4, 3), '     elements:', 12)


('[] is the same as () :', True)


I saw something like array.reshape((-1, 12)), what is that -1 doing?

In [9]:
reshape_verbose(flat, (-1, 1))
reshape_verbose(flat, (-1, 2))
reshape_verbose(flat, (-1, 3))
reshape_verbose(flat, (1, -1))
reshape_verbose(flat, (2, -1))
reshape_verbose(flat, (3, -1))
print #prevent output



[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape((-1, 1)) ->

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
('shape:', (12, 1), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape((-1, 2)) ->

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
('shape:', (6, 2), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape((-1, 3)) ->

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
('shape:', (4, 3), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape((1, -1)) ->

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
('shape:', (1, 12), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape((2, -1)) ->

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
('shape:', (2, 6), '     elements:', 12)


looks like a negative number stretches to fit your set. specifically, it ends up equal to ##elements in array / (product of other dimensions)

You can multiply anything by 1 as many times as you want and it won't change. What happens if you add extra dimensions of 1?

In [10]:
reshape_verbose(flat, [1, 12])
reshape_verbose(flat, [12, 1])
reshape_verbose(flat, [12, 1, 1])
reshape_verbose(flat, [1, 1, 12])
reshape_verbose(flat, [1, 12, 1])
print # prevent output



[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([1, 12]) ->

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
('shape:', (1, 12), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([12, 1]) ->

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
('shape:', (12, 1), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([12, 1, 1]) ->

[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]]
('shape:', (12, 1, 1), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([1, 1, 12]) ->

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]]
('shape:', (1, 1, 12), '     elements:', 12)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
('shape:', (12,), '     elements:', 12)

-> reshape([1, 12, 1]) ->

[[[ 0]
  [ 1]
  [ 2]
